# Generated by Django 3.1 on 2020-08-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='TickerId',
            new_name='TicketId',
        ),
    ]
