# Generated by Django 3.1 on 2020-08-29 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('showid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=20)),
                ('Screen', models.CharField(max_length=20)),
                ('Duration', models.CharField(max_length=20)),
                ('StartTime', models.TimeField(max_length=20)),
                ('Date', models.DateField(max_length=20)),
            ],
        ),
    ]
