# Generated by Django 3.1 on 2020-08-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='availableshows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=20)),
                ('showid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shows.shows')),
            ],
        ),
    ]
