# Generated by Django 3.1 on 2020-08-29 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_availableshows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableshows',
            name='id',
        ),
        migrations.AlterField(
            model_name='availableshows',
            name='showid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
