# Generated by Django 3.1 on 2020-08-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20200829_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='IsExpired',
            field=models.BooleanField(default=False),
        ),
    ]
